spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: chenyh.com
    port: 5672
    username: msg
    password: msg
    listener:
      simple:
        acknowledge-mode: MANUAL
        prefetch: 10
    publisher-confirms: true
    publisher-returns: true