server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway-8085.com
    prefer-ip-address: true

zuul:
  prefix: /getway
  ignored-services: "*"
  routes:
    users-provider:
      path: /user/**
      serviceId: user-provider

info:
  app.name: gateWay
  author: chenyh

spring:
  application:
    name: gateWay
