server:
  port: 3344

spring:
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
      instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: D:\IDEA Code\SpringCloudConfigRepo

---
spring:
  profiles: cloud
  cloud:
    config:
      server:
        git:
          uri: git@github.com:SimpleChenyh/SpringCloudConfigRepo.git #GitHub上面的git仓库名字
          #search-paths: ${application}-config
          ignore-local-ssh-settings: true
          strict-host-key-checking: false
          passphrase:
          private-key:

